import { createRequire } from 'node:module'
import fs from 'node:fs'
const require = createRequire('file:///C:/Users/xianyv/.workbuddy/binaries/node/workspace/')
const puppeteer = require('puppeteer-core')
const base = process.argv[2] || 'http://127.0.0.1:5173'
fs.mkdirSync('outputs', { recursive: true })
const browser = await puppeteer.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true, args: ['--no-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader'] })
const results = [], errors = []
try {
 const page = await browser.newPage()
 page.setDefaultTimeout(30000)
 page.on('pageerror', e => errors.push(String(e)))
 page.on('console', m => { if(m.type() === 'error') errors.push(m.text()) })
 await page.setViewport({ width:1440, height:900 })
 await page.goto(base + '/login', { waitUntil:'domcontentloaded' })
 await page.evaluate(async () => {
   const c = (await (await fetch('/api/auth/captcha')).json()).data
   const code = [...atob(c.svg.split('base64,')[1]).matchAll(/<text[^>]*>([^<])<\/text>/g)].map(m=>m[1]).join('')
   const r = await (await fetch('/api/auth/login', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'admin',password:'admin123',captchaId:c.id,captchaCode:code,captcha:code})})).json()
   if(!r.data?.token) throw new Error('Login failed: '+JSON.stringify(r))
   localStorage.setItem('sc_token',r.data.token); localStorage.setItem('sc_user',JSON.stringify(r.data.user))
 })
 const diagnostic = () => page.evaluate(() => document.querySelector('.care-room').__vueParentComponent.exposed.diagnostics())
 for (const width of (process.env.FOCUS_ONLY ? [] : [1440,1024,768,375])) {
  await page.setViewport({width,height:width===375?812:900})
  for (const theme of ['room','corridor','nursing','dining','rehab']) {
   await page.goto(`${base}/dashboard?theme=${theme}${theme==='room'?'&room=101':''}`,{waitUntil:'domcontentloaded'})
   await page.waitForFunction(() => document.querySelector('.care-room')?.__vueParentComponent?.exposed?.diagnostics().calls > 0)
   await page.waitForFunction(() => document.querySelector('.care-room')?.__vueParentComponent?.exposed?.diagnostics().actors > 0)
   await new Promise(r=>setTimeout(r,500))
   const d = await diagnostic()
   const overflow = await page.evaluate(()=>Math.max(0,document.documentElement.scrollWidth-innerWidth))
   results.push({width,theme,actors:d.actors,bones:d.bones,particles:d.particles,calls:d.calls,triangles:d.triangles,overflow})
   if(width===1440 || (width===375 && theme==='room')) await page.screenshot({path:`outputs/care-${theme}-${width}.png`})
   if(d.particles || !d.bones || overflow) throw new Error('Scene assertion failed')
  }
 }
 await page.setViewport({width:1440,height:900})
 await page.goto(base+'/dashboard?theme=room&room=102',{waitUntil:'domcontentloaded'})
 await page.waitForFunction(()=>document.querySelector('.care-room')?.__vueParentComponent?.exposed?.diagnostics().calls>0)
 await new Promise(r=>setTimeout(r,800))
 const empty=await diagnostic(); if(empty.actors!==0) throw new Error('Empty room contains actors')
 results.push({test:'empty102',actors:empty.actors})
 await page.goto(base+'/dashboard?theme=room&room=101',{waitUntil:'domcontentloaded'})
 await page.waitForFunction(()=>document.querySelector('.care-room')?.__vueParentComponent?.exposed?.diagnostics().actors===2)
 await page.click('.model-toolbar button:nth-child(2)')
 const paused=await diagnostic(); await new Promise(r=>setTimeout(r,450)); const after=await diagnostic()
 if(!paused.paused || JSON.stringify(paused.pose)!==JSON.stringify(after.pose)) throw new Error('Pause not stable')
 await page.click('.model-toolbar button:nth-child(3)'); if(!(await diagnostic()).skeleton) throw new Error('Skeleton toggle failed')
 const before=await diagnostic(); await page.evaluate(()=>document.querySelector('.care-room').__vueParentComponent.exposed.rotateBy(1)); const rotated=await diagnostic()
 if(JSON.stringify(before.camera)===JSON.stringify(rotated.camera)) throw new Error('Virtual rotate inactive')
 results.push({test:'pause-skeleton-virtual-control',ok:true})
 await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}])
 if(!(await diagnostic()).paused) throw new Error('Reduced motion ignored')
 results.push({test:'reduced-motion',ok:true})
 await page.goto(base+'/overview',{waitUntil:'domcontentloaded'})
 await page.waitForSelector('.campus3d canvas')
 await new Promise(r=>setTimeout(r,1100))
 await page.screenshot({path:'outputs/care-overview-1440.png'})
 const campus = () => page.evaluate(()=>document.querySelector('.campus3d').__vueParentComponent.exposed.diagnostics())
 await page.evaluate(()=>document.querySelector('.campus3d').__vueParentComponent.exposed.setFloor(2))
 await new Promise(r=>setTimeout(r,700))
 const floor = await campus()
 if(floor.activeFloor!==2 || floor.selectable.some(o=>o.kind==='room' && !o.code.startsWith('2'))) throw new Error('Floor pick filter failed')
 await page.evaluate(()=>document.querySelector('.campus3d').__vueParentComponent.exposed.resetView())
 if((await campus()).activeFloor!==0) throw new Error('Campus reset failed')
 const canvas = await page.$('.campus3d canvas'), bounds = await canvas.boundingBox()
 const start=await campus()
 await page.mouse.move(bounds.x+bounds.width*0.65,bounds.y+bounds.height*0.6)
 await page.mouse.down(); await page.mouse.move(bounds.x+bounds.width*0.75,bounds.y+bounds.height*0.62,{steps:12}); await page.mouse.up()
 await new Promise(r=>setTimeout(r,300))
 if(JSON.stringify(start.camera)===JSON.stringify((await campus()).camera)) throw new Error('Campus drag inactive')
 results.push({test:'overview-floor-reset-drag',ok:true})
 const clickFloor = (text) => page.evaluate((t)=>{ const b=[...document.querySelectorAll('.floor-row')].find(el=>el.textContent.includes(t)); if(!b) throw new Error('Floor row missing: '+t); b.click() },text)
 await clickFloor('2F'); await new Promise(r=>setTimeout(r,600))
 if((await campus()).activeFloor!==2) throw new Error('Overview floor row did not filter scene')
 await clickFloor('2F'); await new Promise(r=>setTimeout(r,600))
 if((await campus()).activeFloor!==0) throw new Error('Overview floor toggle-off failed')
 results.push({test:'overview-panel-floor',ok:true,calls:(await campus()).calls})
 if(await page.$('.watch-row')){
  const code=await page.$eval('.watch-row b',e=>e.textContent.trim())
  await page.click('.watch-row'); await page.waitForSelector('.hud-detail')
  const title=await page.$eval('.hud-detail h3',e=>e.textContent.trim())
  const focused=(await campus()).selectable.length
  if(title!==`${code}室` || !focused) throw new Error('Watch row focus mismatch')
  results.push({test:'overview-watch-focus',room:code,focused})
 }
 await page.setViewport({width:375,height:812,hasTouch:true,isMobile:true})
 await page.goto(base+'/dashboard?theme=room&room=101',{waitUntil:'domcontentloaded'})
 await page.waitForFunction(()=>document.querySelector('.care-room')?.__vueParentComponent?.exposed?.diagnostics().actors===2)
 await page.waitForSelector('.stage-tools')
 const mobileBefore=await diagnostic()
 await page.click('.stage-tools button[aria-label="向左旋转"]')
 if(JSON.stringify(mobileBefore.camera)===JSON.stringify((await diagnostic()).camera)) throw new Error('Touch toolbar inactive')
 results.push({test:'touch-toolbar',ok:true})
 await page.setViewport({width:1440,height:900,hasTouch:false,isMobile:false})
 await page.goto(base+'/dashboard?theme=room&room=101',{waitUntil:'domcontentloaded'})
 await page.waitForFunction(()=>document.querySelector('.care-room')?.__vueParentComponent?.exposed?.diagnostics().actors===2)
 const roomCanvas=await (await page.$('.care-room canvas')).boundingBox()
 const resident=(await diagnostic()).pickables.find(o=>!o.name.includes('护理') && !o.name.includes('按钮') && !o.name.includes('柜') && o.x>0.35 && o.x<0.8 && o.y>0.2 && o.y<0.8)
 if(resident){
  const x=roomCanvas.x+roomCanvas.width*resident.x,y=roomCanvas.y+roomCanvas.height*resident.y
  await page.mouse.click(x,y); await page.waitForSelector('.detail')
  const selectedName=await page.$eval('.detail .panel-title',e=>e.textContent)
  await page.click('.detail .close')
  const focusBefore=await diagnostic(); await page.mouse.click(x,y,{count:2,delay:60}); await new Promise(r=>setTimeout(r,650))
  const cameraMoved=JSON.stringify(focusBefore.camera)!==JSON.stringify((await diagnostic()).camera)
  if(!cameraMoved) throw new Error('Double click focus inactive')
  results.push({test:'pick-doubleclick',selected:selectedName,cameraMoved})
 } else throw new Error('No accessible resident for pick test')
 await page.evaluate(()=>document.querySelectorAll('.theme-switch button')[1].click())
 await page.waitForFunction(()=>location.search.includes('theme=corridor') && !location.search.includes('room='))
 await page.evaluate(()=>document.querySelectorAll('.theme-switch button')[0].click())
 await page.waitForFunction(()=>document.querySelector('.care-room')?.__vueParentComponent?.exposed?.diagnostics().theme==='room')
 results.push({test:'theme-switch-room-scope-clear',ok:true})
 const fallbackPage=await browser.newPage()
 await fallbackPage.evaluateOnNewDocument(()=>{ const original=HTMLCanvasElement.prototype.getContext; HTMLCanvasElement.prototype.getContext=function(type,...args){return String(type).startsWith('webgl')?null:original.call(this,type,...args)} })
 await fallbackPage.goto(base+'/dashboard',{waitUntil:'domcontentloaded'})
 await fallbackPage.waitForSelector('.gl-fallback')
 results.push({test:'webgl-fallback',ok:true})
 await fallbackPage.close()
} catch(e) { errors.push(String(e)) } finally { await browser.close() }
fs.writeFileSync('outputs/care-audit.json',JSON.stringify({at:new Date().toISOString(),base,results,errors},null,2))
console.log(JSON.stringify({results,errors},null,2))
process.exitCode=errors.length?1:0
